displayName: ResponseHeaderForward

type: middleware

import: github.com/ditkrg/traefik-response-header-forward-plugin

summary: A middleware to add headers from request to response.

testData:
  requestHeaders:
    - name: userId1
    - name: userId2
